### ISSUE TITLE
question about gain level of microphone

### ISSUE THREAD

**Issue by michal800106** [hselasky/virtual_oss#16]
Hi, I'm using virtual_oss and works very good.
I have one problem with it, during videoconferencing mic level is too low on both bluetooth mic and internal one and coworkers complain about it.
I have an question if there is possibility to increase gain on mic in virtual_oss?

**Comment by hselasky** [comment]
Hi,

If you create the control device and install the GUI (virtual_oss_ctl) you can both apply a compressor (recommended) and change the gain per DSP device. The gain is logarithmic, 1x, 2x, 4x and so on.

--HPS
![image](https://user-images.githubusercontent.com/1541461/129353006-e0587170-629f-4a09-a55f-47a3f92eba86.png)

**Comment by michal800106** [comment]
thank you. Now all is working beautifully. I appreciate very fast response.
