### ISSUE TITLE
bluetooth sdp_open sessions with an error are never closed

### ISSUE THREAD

**Issue by patrickSpaceSurfer** [hselasky/virtual_oss#18]
I have come across an issue in backend_bt.c which leads to resource exhaustion. I ran out of sockets on my desktop when I left virtual_oss running before turning my bluetooth headphones on.

In backend_bt.c, when sdp_open returns with an error, the code logs "Could not open SDP", but never closes the sdp session object.
The sdp_open function creates a PF_BLUETOOTH socket (verified with truss) and since the operation is retried every few seconds, eventually you run out of sockets.

There is a similar piece of code in bt_speaker.c, that uses sdp_open_local but doesn't close the object on error.

I have a patch that fixes the issue for me. I tried to attach it to this issue, but github does not recognize it as a patch no matter what file name extension I use. The patch is trivial but I can clone and create a pull request if you want.

**Comment by hselasky** [comment]
I think if you name it .txt, it works. Or just send it to me by e-mail: hps@selasky.org .

Good catch! I see the resource leakage. Which e-mail do you want to have in the commit message as author? Or do you just want me to write Submitted-by: XXX?

--HPS

**Comment by patrickSpaceSurfer** [comment]
I did email you a couple of days ago from patrick at spacesurfer.com

It looks like I can upload .txt files, I have attached the patch to this comment. Feel free to make any changes. If you do want to credit me as author you can use the email address patrick at spacesurfer.com

Thanks for your great piece of software. 

[virtual_oss.patch.txt](https://github.com/hselasky/virtual_oss/files/11581644/virtual_oss.patch.txt)

Patrick

**Comment by hselasky** [comment]
I was a bit busy this week, but it is fixed now.

I made a minor change to your patch, skipping those NULL checks, because sdp_close() is NULL safe already.

Please test!

Thank you for using and supporting virtual_oss !

https://cgit.freebsd.org/ports/commit/?id=46e258533e697406afdbd3d804282d644befc17a
