### ISSUE TITLE
Failing to close diconnected USB audio device

### ISSUE THREAD

**Issue by therontarigo** [hselasky/virtual_oss#6]
Since commit dd05e2c virtual_oss no longer closes /dev/dspN for a USB audio device which has been physically disconnected.  This has rendered virtual_oss no longer a good workaround for https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=194727#c9.

    -                       if (len <= 0)
    +
    +                       /* check for error only */
    +                       if (len < 0)
                                    break;

Here's what is happening when the device is disconnected:
- The driver no longer consumes samples, so result of SNDCTL_DSP_GETODELAY (via `tx_be->delay`) becomes larger than `(4 * buffer_dsp_tx_size)`.
- The "Simple fix for jitter ... Skip data when too much." sets `blocks = 0`.  With no blocks to write, there is no write attempted, so the failure of the device to be writable is never discovered and the program loops through this condition indefinitely.

Changing the "too much data" case to set `blocks = 1` works around the problem, however it takes much longer, about 3 seconds, from `tx_be->delay` result first exceeding tx size (which happens immediately when disconnecting the USB) before writes fail and virtual_oss disconnects.

Unconditionally entering into `need_delay = true; break;` when `blocks > (4 * buffer_dsp_tx_size)` gets virtual_oss to disconnect immediately, but this reintroduces the problem of delays during normal operation that commit dd05e2c was meant to fix.

**Comment by therontarigo** [comment]
It might be a separate issue, but implicating the same code: "Skip data when too much." ... `blocks = 0` if I understand correctly is causing audio data, which the source application thinks have been successfully played, to be discarded.  I haven't studied far enough to see how virtual_oss makes sure to only consume as many samples from the source application as the hardware is actually consuming, but considering that SNDCTL_DSP_GETODELAY is only used in one place for actually discarding data, I'm concerned it might not be implemented at all.  It looks like the logic is using system time clock instead of DSP sample clock for rate at which samples are consumed, the latter being what direct OSS uses.

**Comment by hselasky** [comment]
Hi,

I'm using version 1.2.5 of virtual_oss and I cannot reproduce this:

1) virtual_oss -S -C 2 -c 2 -b 16 -r 48000 -s 384 -f /dev/dspN -d dsp
2) usbconfig -d X.Y reset

works fine and audio comes back!

Perhaps you are using a different command line?

--HPS

**Comment by hselasky** [comment]
I think this should be patched in the kernel, that DSP read/write should return an error instantly when we are in detach mode.

**Comment by therontarigo** [comment]
I was using virtual_oss -S -c 2 -r 96000 -b 24 -s 256 -P /dev/dsp3 -R /dev/null -a 0 -d dsp -t vdsp.ctl
Set some sysctls back to their defaults, now have:
```
hw.usb.uaudio.buffer_ms: 8
hw.usb.uaudio.default_channels: 0
hw.usb.uaudio.default_bits: 32
hw.usb.uaudio.default_rate: 0
hw.usb.uaudio.debug: 0
hw.snd.basename_clone: 0
hw.snd.compat_linux_mmap: 0
hw.snd.syncdelay: -1
hw.snd.usefrags: 0
hw.snd.vpc_reset: 0
hw.snd.vpc_0db: 45
hw.snd.vpc_autoreset: 1
hw.snd.timeout: 5
hw.snd.latency_profile: 1
hw.snd.latency: 2
hw.snd.report_soft_matrix: 1
hw.snd.report_soft_formats: 1
dev.pcm.3.bitperfect: 0
dev.pcm.3.buffersize: 0
dev.pcm.3.play.vchanformat: s24le:2.0
dev.pcm.3.play.vchanrate: 96000
dev.pcm.3.play.vchanmode: adaptive
```
Still reproduces the problem.  I can't imagine there is any hardware-dependence of this issue since the hardware is gone by the time there is a problem.

If this is fixed in kernel, how will virtual_oss detect it?  ioctl SNDCTL_DSP_GETODELAY would need to fail, since otherwise the large value means there is never a write happening to encounter a write failure.

BTW I'm getting good results with
```
			/* Get output delay in bytes */
			tx_be->delay(tx_be, &blocks);

			if (blocks > (4 * buffer_dsp_tx_size)) {
				int wait = virtual_oss_delay() / 2;
				usleep(wait / 1000);
				int blocks2;
				tx_be->delay(tx_be, &blocks2);
				if (blocks2 == blocks) {
					// dsp stuck
					need_delay = true;
					break;
				}
			}

```

**Comment by hselasky** [comment]
I see what is going on there. Give me an hour and I'll make a good fix for that!

**Comment by hselasky** [comment]
This patch should fix your issue:
https://svnweb.freebsd.org/changeset/base/358629

If not please re-open this issue.

Thank you!

**Comment by therontarigo** [comment]
The original issue is fixed when running on -CURRENT.  Thanks!

However the time for virtual_oss to reconnect after USB reset is still longer than it should be (4 seconds vs. 1 second if I use the code snippet above).

**Comment by hselasky** [comment]
I might consider patching this later on, when people have upgraded their kernels.
