### ISSUE TITLE
virtual_oss starts to early

### ISSUE THREAD

**Issue by rozhuk-im** [hselasky/virtual_oss#9]
```virtual_oss: Could not open '/dev/sndstat': No such file or directory```

Because virtual_oss start before kld_list processed and before webcamd.

kld_list - required because it loads sound modules (I have custom kernel) and GPU drivers. I use HDMI sound output, so even with GENERIC it will fail to get proper sound output device.
webcamd - required because webcam mic used as sound input device.

Probably webcamd should also start a bit early, before sndiod.

**Comment by hselasky** [comment]
What if cuse.ko is in the kld_list? Do we have a chicken egg problem here?

**Comment by hselasky** [comment]
virtual_oss could also wait and retry opening the sndstat file.

**Comment by rozhuk-im** [comment]
If cuse is in kld_list then we have no choice and must wait before kld_list processed before start virtual_oss.

**Comment by hselasky** [comment]
I think we can do something like that.
What should the timeout value be?  60 seconds or infinite?

**Comment by rozhuk-im** [comment]
Timeout for ...?

**Comment by rozhuk-im** [comment]
Can you add ```REQUIRE: webcamd, kld_list``` ?

**Comment by hselasky** [comment]
Yes, I see that kld_list may be useful for both webcamd and virtual_oss, but I don't see why webcamd is required for virtual_oss ?

**Comment by rozhuk-im** [comment]
webcamd may provide some sound devices for virtual_oss, like mic from webcams.

**Comment by hselasky** [comment]
Right now webcamd does not support any propritary audio. All audio goes through the USB audio interface driver in the FreeBSD kernel.

**Comment by rozhuk-im** [comment]
Oh, yes, sorry, then kld_list should be enough as REQUIRED dep to start virtual_oss.

**Comment by hselasky** [comment]
No problem.
https://github.com/hselasky/virtual_oss/commit/0711bb4579358f12d732af257f9d17f7520bb9c8

Will try to get this upstreamed next time I sync the package. Is this issue urgent?

**Comment by rozhuk-im** [comment]
Thanks!
I write by hand ```REQUIRED webcamd``` and this will work until next virtual_oss update :)
Probably webcamd should have this change too?

**Comment by hselasky** [comment]
Looks like it is called kld and not kld_list.

/etc/rc.d/kld:# PROVIDE: kld

https://github.com/hselasky/virtual_oss/commit/653c2b9cfc536e55ec9a2785bde3832983d7217c
